title: Hamasak1 osu! skins
author: Hamasak1
email: Not Happening
description: > # this means to ignore newlines until "baseurl:"
  Hamasak1 Skins

# social links
twitter_username: Not happening # DO NOT include the @ character, or else the build will fail!
github_username:  Hamasak1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
